# Generated by Django 2.0.3 on 2018-07-13 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('itemType', models.CharField(max_length=100)),
                ('acquiredDate', models.CharField(max_length=20)),
                ('acquiredTime', models.CharField(max_length=20)),
                ('acquiredPlace', models.CharField(max_length=100)),
                ('storagePlace', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_found', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('itemType', models.CharField(max_length=100)),
                ('acquiredDate', models.CharField(max_length=20)),
                ('acquiredTime', models.CharField(max_length=20)),
                ('acquiredPlace', models.CharField(max_length=100)),
                ('storagePlace', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_lost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
