# Generated by Django 2.0.3 on 2018-07-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
